1
basic setting:
beta = 1200.0
lr decay /iters = 160
number of class to be attacked = 10
learning rate = 0.0010000
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "cifar_manr.py", line 232, in <module>
    main()
  File "cifar_manr.py", line 72, in main
    train (opt,netD,netT,optimizer_G,train_loader_single, eps, optimizers, schedulers, mean_arr, stddev_arr)
  File "cifar_manr.py", line 130, in train
    logist_B = netT(clip_A)
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 71, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfhan/MAN/models/identity_map_resnet_for_cifar.py", line 114, in forward
    out = self.layer1(out)
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfhan/MAN/models/identity_map_resnet_for_cifar.py", line 83, in forward
    out = F.relu(self.bn2(self.conv1(out)))
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/jfhan/anaconda2/envs/dlight/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCStorage.cu:58
